site_name: Islandora Workbench
site_dir: site
docs_dir: docs
site_description: Documentation for Islandora Workbench
dev_addr: 'localhost:8111'
repo_url: https://github.com/mjordan/islandora_workbench_docs
theme: material
nav:
    - Home: index.md
    - Requirements and installation: installation.md
    - Configuration: configuration.md
    - Checking configuration and input data: check.md
    - Preparing your data: preparing_data.md
    - Field data (Drupal and CSV): fields.md
    - Ignoring CSV rows and columns: ignoring_csv_rows_and_columns.md
    - CSV field templates: field_templates.md
    - Creating paged, compound, and collection content: paged_and_compound.md
    - Creating nodes without media: nodes_only.md
    - Creating nodes from files: creating_nodes_from_files.md
    - Creating taxonomy terms: creating_taxonomy_terms.md
    - Assigning URL aliases: aliases.md
    - Adding alt text to images: alt_text.md
    - Rolling back nodes and media: rolling_back.md
    - Configuring media types: media_types.md
    - Updating nodes: updating_nodes.md
    - Deleting nodes: deleting_nodes.md
    - Adding media to nodes: adding_media.md
    - Adding multiple media: adding_multiple_media.md
    - Creating media track files: media_track_files.md
    - Deleting media: deleting_media.md
    - Generating CSV files: generating_csv_files.md
    - Creating nodes from the sample data: sample_data.md
    - Exporting Islandora 7 content: exporting_islandora_7_content.md
    - Generating sample Islandora content: generating_sample_content.md
    - Hooks: hooks.md
    - Fixity checking: fixity.md
    - Logging: logging.md
    - Cancelling Workbench: cancelling.md
    - Quick delete: quick_delete.md
    - Workflows: workflows.md
    - Reducing Workbench's impact on Drupal: reducing_load.md
    - Known limitations: limitations.md
    - Roadmap (Fall 2021): roadmap.md
    - Troubleshooting: troubleshooting.md
    - Change log: changelog.md
    - Development guide: development_guide.md
markdown_extensions:
  - admonition
extra_css:
    - css/extra.css
edit_uri: 'edit/main/docs/'
